#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# vps-setup.sh — Idempotent VPS provisioning for fpc-back
#
# Creates the directory structure, .env placeholders, SSH deploy user,
# Docker network, and pulls base images needed by both environments.
#
# Usage:   sudo bash scripts/vps-setup.sh
#          (provide FPC_DEV_DB_PASSWORD, FPC_PROD_DB_PASSWORD,
#           FPC_DEV_JWT_SECRET, FPC_PROD_JWT_SECRET as env vars)
#
# Idempotent: safe to run multiple times — existing .env files are NOT
#             overwritten, users are NOT recreated if they already exist.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────
FPC_BASE="/opt/fpc"
DEV_DIR="${FPC_BASE}/dev"
PROD_DIR="${FPC_BASE}/prod"
DEPLOY_USER="deploy"
DOCKER_NETWORK="fpc-net"

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()  { echo -e "${GREEN}[OK]${NC}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
err()  { echo -e "${RED}[ERR]${NC}  $*" >&2; }
info() { echo -e "${BLUE}[INFO]${NC} $*"; }

# ── Root check ───────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  err "This script must be run as root (sudo)."
  exit 1
fi

# ── Step 1: Verify Docker and Docker Compose ─────────────────────────────────
echo ""
info "Step 1/6: Verifying Docker installation..."

if ! command -v docker &>/dev/null; then
  err "Docker is not installed. Please install Docker first."
  err "  curl -fsSL https://get.docker.com | sh"
  exit 1
fi
log "Docker $(docker --version | awk '{print $3}' | tr -d ',') found"

if docker compose version &>/dev/null; then
  log "Docker Compose (plugin) found"
elif command -v docker-compose &>/dev/null; then
  log "Docker Compose (standalone) found"
else
  err "Docker Compose is not installed."
  err "  sudo apt-get install docker-compose-plugin  (Debian/Ubuntu)"
  err "  or: sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
  exit 1
fi

# ── Step 2: Create directory structure ───────────────────────────────────────
echo ""
info "Step 2/6: Creating directory structure..."

mkdir -p "${DEV_DIR}" "${PROD_DIR}"
log "Created: ${DEV_DIR}"
log "Created: ${PROD_DIR}"

# ── Step 3: Create .env files with placeholders (skip if existing) ───────────
echo ""
info "Step 3/6: Setting up .env files..."

create_env_file() {
  local env_name="$1"
  local env_dir="$2"
  local db_password_var="$3"
  local jwt_secret_var="$4"
  local db_name="$5"
  local env_file="${env_dir}/.env"

  if [ -f "$env_file" ]; then
    warn ".env already exists at ${env_file} — skipping (delete it manually to regenerate)"
    return
  fi

  local db_password="${!db_password_var:-replace-me-${env_name}-db-password}"
  local jwt_secret="${!jwt_secret_var:-replace-me-${env_name}-jwt-secret}"

  cat > "$env_file" << EOF
# ════════════════════════════════════════════════════════════════
# fpc-back ${env_name} environment — auto-generated by vps-setup.sh
# ════════════════════════════════════════════════════════════════

# PostgreSQL
DB_USERNAME=postgres
DB_URL=jdbc:postgresql://postgres:5432/${db_name}
DB_PASSWORD=${db_password}

# JWT
JWT_SECRET=${jwt_secret}
JWT_ACCESS_EXPIRATION=900000
JWT_REFRESH_EXPIRATION=604800000

# Docker image (updated by CI/CD)
IMAGE_TAG=${env_name}-latest
EOF

  log "Created: ${env_file}"
}

create_env_file "dev"  "${DEV_DIR}"  "FPC_DEV_DB_PASSWORD"  "FPC_DEV_JWT_SECRET"  "fpc_db_dev"
create_env_file "prod" "${PROD_DIR}" "FPC_PROD_DB_PASSWORD" "FPC_PROD_JWT_SECRET" "fpc_db"

# ── Step 4: Create deploy user ───────────────────────────────────────────────
echo ""
info "Step 4/6: Configuring deploy user..."

if id "${DEPLOY_USER}" &>/dev/null; then
  warn "User '${DEPLOY_USER}' already exists — skipping creation"
else
  useradd --system --create-home --shell /bin/bash "${DEPLOY_USER}"
  log "Created user: ${DEPLOY_USER}"
fi

# Add to docker group so deploy user can run docker commands
if groups "${DEPLOY_USER}" | grep -q '\bdocker\b'; then
  warn "User '${DEPLOY_USER}' is already in docker group"
else
  usermod -aG docker "${DEPLOY_USER}"
  log "Added ${DEPLOY_USER} to docker group"
fi

# Create .ssh directory for deploy user
SSH_DIR="/home/${DEPLOY_USER}/.ssh"
if [ ! -d "${SSH_DIR}" ]; then
  mkdir -p "${SSH_DIR}"
  chmod 700 "${SSH_DIR}"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "${SSH_DIR}"
  log "Created: ${SSH_DIR}"
fi

# Placeholder for authorized_keys (add your CI public key manually)
AUTH_KEYS="${SSH_DIR}/authorized_keys"
if [ ! -f "${AUTH_KEYS}" ]; then
  touch "${AUTH_KEYS}"
  chmod 600 "${AUTH_KEYS}"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "${AUTH_KEYS}"
  warn "Created empty ${AUTH_KEYS} — add your GitHub Actions public key manually"
fi

# ── Step 5: Set permissions ──────────────────────────────────────────────────
echo ""
info "Step 5/6: Setting permissions..."

chmod 750 "${FPC_BASE}" "${DEV_DIR}" "${PROD_DIR}"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${FPC_BASE}"

# Ensure .env files are readable only by owner
find "${FPC_BASE}" -name ".env" -exec chmod 600 {} \;
find "${FPC_BASE}" -name ".env" -exec chown "${DEPLOY_USER}:${DEPLOY_USER}" {} \;

log "Permissions set: dirs=750, .env files=600, owner=${DEPLOY_USER}"

# ── Step 6: Create Docker network and pull base images ───────────────────────
echo ""
info "Step 6/6: Docker network and base images..."

# Create shared bridge network (idempotent: '|| true' if already exists)
if docker network inspect "${DOCKER_NETWORK}" &>/dev/null; then
  warn "Docker network '${DOCKER_NETWORK}' already exists"
else
  docker network create --driver bridge "${DOCKER_NETWORK}"
  log "Created Docker network: ${DOCKER_NETWORK}"
fi

# Pull base images (cached if already present)
echo ""
info "Pulling base images..."
docker pull postgres:16-alpine
docker pull eclipse-temurin:21-jre-noble
log "Base images up to date"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 VPS Setup Complete                             ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  Directories:                                                  ║"
echo "║    ${DEV_DIR}"
echo "║    ${PROD_DIR}"
echo "║                                                                ║"
echo "║  Deploy user:    ${DEPLOY_USER} (in docker group)"
echo "║  Docker network: ${DOCKER_NETWORK}"
echo "║                                                                ║"
echo "║  NEXT STEPS:                                                   ║"
echo "║    1. Edit .env files with real passwords:                     ║"
echo "║       vim ${DEV_DIR}/.env"
echo "║       vim ${PROD_DIR}/.env"
echo "║    2. Add CI public key to:                                    ║"
echo "║       ${SSH_DIR}/authorized_keys"
echo "║    3. Copy compose files (done automatically by CI/CD):        ║"
echo "║       docker-compose.dev.yml  → ${DEV_DIR}/"
echo "║       docker-compose.prod.yml → ${PROD_DIR}/"
echo "║    4. Set GitHub Secrets (see .env.example in repo):           ║"
echo "║       SSH_HOST, SSH_USER, SSH_PRIVATE_KEY,                     ║"
echo "║       DB_PASSWORD_DEV, DB_PASSWORD_PROD,                       ║"
echo "║       JWT_SECRET_DEV, JWT_SECRET_PROD, GHCR_TOKEN              ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
